### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by fiorrr** [planetk/homebridge-netatmo#11]
Hi!

I'm getting this error when starting Homebridge with the plugin activated:

/usr/local/lib/node_modules/homebridge/lib/server.js:176
throw err;
^
SyntaxError: Unexpected token ]
at Object.parse (native)
at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:170:19)
at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Function.Module.runMain (module.js:467:10)

How can this be fixed?

Client ID, Secret, Username and Password are set correctly.

Thanks!

**Comment by fiorrr** [comment]
I finally found the error myself.
