### ISSUE TITLE
Problem loading accessorie

### ISSUE THREAD

**Issue by jpg32** [planetk/homebridge-netatmo#12]
Hi, I try today your pluggin and I've got this issue : 

`[6/22/2016, 4:17:38 PM] Loaded plugin: homebridge-netatmo
[6/22/2016, 4:17:38 PM] Registering platform 'homebridge-netatmo.netatmo'
[6/22/2016, 4:17:38 PM] ---
[6/22/2016, 4:17:38 PM] Loaded config.json with 1 accessories and 1 platforms.
[6/22/2016, 4:17:38 PM] ---
[6/22/2016, 4:17:38 PM] Loading 1 platforms...
[6/22/2016, 4:17:38 PM] [netatmo weather] Initializing netatmo platform...
[6/22/2016, 4:17:38 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:46
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:233:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)`

Do you have an idea ?

**Comment by planetk** [comment]
Hi,

are you sure, that you changed the config.json file in a valid way?

Looks like the name can not be read. Maybe you can try with an online json validator?

Kind regards
Stefan
