### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by Alexis1537** [planetk/homebridge-netatmo#26]
Dear all, apologies for the rather simple question - I'm very new to JSON and am struggling with a parsing error which I cannot resolve for the config file for a netatmo home bridge plugin. In essence: I have put the following in the config file:

"platforms": [{
	"platform": "netatmo",
	"name": "netatmo platform",
	"ttl": 5,
	*
	"deviceTypes": [ "weatherstation",  "thermostat",  "welcome" ],
	*
	"auth": {
		"client_id": "xxxxxxxxxd428b45bd",
		"client_secret": "xxxxxxxxx6mjB2QluBZlYrfZUE",
		"username": "alexisxxxxx@.com",
		"password": "Vxxxxxxxxxx"
	}
}],

The "Xs" are just to anonymise a bit. The JSONLint site gives me the following error:

Error: Parse error on line 1:
"platforms": [{	"platform": "n
-----------^
Expecting 'EOF', '}', ',', ']', got ':'

I pasted the text exactly as was shown in previous post but neither JSONLint nor Homebridge seem to like it. Can you help? Many thanks! Alex

**Comment by planetk** [comment]
Hi, please remove the asterisks ( * )

**Comment by Alexis1537** [comment]
Many thanks Stefan. Unfortunately, I get the same error:

[9/3/2016, 11:30:09 AM] Loaded plugin: homebridge-netatmo
[9/3/2016, 11:30:09 AM] Registering platform 'homebridge-netatmo.netatmo'
[9/3/2016, 11:30:09 AM] ---
[9/3/2016, 11:30:09 AM] There was a problem reading your config.json file.
[9/3/2016, 11:30:09 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[9/3/2016, 11:30:09 AM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:176
    throw err;
    ^

SyntaxError: Unexpected token :
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:170:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

**Comment by planetk** [comment]
Is there anything after the last comma? If not please remove the comma as well. Sorry I'm with my mobile only, so i can't really check today.

**Comment by Alexis1537** [comment]
Hi Stefan! OK, I've managed to fix the JSOn syntax with the following:

{
	"platform": "netatmo",
	"name": "netatmo platform",
	"ttl": 5,
	"deviceTypes": [
		"weatherstation",
		"thermostat",
		"welcome"
	],
	"auth": {
		"client_id": "xxxxxxxxxxbd",
		"client_secret": "xxxxxxxxxxE",
		"username": "alexisxxxxxx@xx.com",
		"password": "xxxxxxxxx"
	}
}

However, now I'm getting a new error, namely:

/usr/local/lib/node_modules/homebridge/lib/server.js:181
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:181:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

It says it cannot read the property "username". Is that the actual username I've put in (which is the login for my Netatmo account)? Again, my apologies for being a bit dim. Your help is much appreciated! Alex

**Comment by planetk** [comment]
Looks like your config is missing the homebridge specific Part.
Please add:
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

**Comment by Alexis1537** [comment]
Hi Stefan, many thanks! Home bridge now runs and I was able to locate Homebridge in the Eve app on iOS. Now the only left to do is to work out how to make my Weatherstation appear (it's simply not appearing as an accessory).

**Comment by Alexis1537** [comment]
OK, I'm still perplexed. The log says that:

[9/3/2016, 2:41:12 PM] Loaded plugin: homebridge-netatmo
[9/3/2016, 2:41:12 PM] Registering platform 'homebridge-netatmo.netatmo'
[9/3/2016, 2:41:12 PM] ---
[9/3/2016, 2:41:12 PM] Loaded config.json with 0 accessories and 0 platforms.
[9/3/2016, 2:41:12 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
I'm worried about the "loaded config.json with 0 accessories and 0 platforms". The config file parsed successfully though. Any thoughts?

Here's the config wording again:

{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        "platform": "netatmo",
        "name": "netatmo platform",
        "ttl": 5,
        "deviceTypes": [
                "weatherstation",
                "thermostat",
                "welcome"
        ],
        "auth": {
                "client_id": "idxxxxx",
                "client_secret": "secretxxx",
                "username": "email address for netatmo account",
                "password": "password"
        }
}

**Comment by planetk** [comment]
Looks like you stoppend the platforms:[ tag

**Comment by Alexis1537** [comment]
Thanks Stefan - it looks much better now! Now my only challenge is getting the Eve app to see  Homebridge. It used to appear and now it's gone! Here's the log for Homebridge in case you find a clue (you have been brillant!):

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/3/2016, 4:16:44 PM] Loaded plugin: homebridge-netatmo
[9/3/2016, 4:16:44 PM] Registering platform 'homebridge-netatmo.netatmo'
[9/3/2016, 4:16:44 PM] ---
[9/3/2016, 4:16:44 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/3/2016, 4:16:44 PM] ---
[9/3/2016, 4:16:44 PM] Loading 1 platforms...
[9/3/2016, 4:16:44 PM] [netatmo platform] Initializing netatmo platform...
[9/3/2016, 4:16:44 PM] [netatmo platform] Creating NetatmoPlatform...
[9/3/2016, 4:16:48 PM] [netatmo platform] refreshing weatherstation device xxxxxxx:22 (Armstrong Atmo Station)
[9/3/2016, 4:16:48 PM] [netatmo platform] refreshing weatherstation module xxxxxxxx:6e (Armstrong Atmo Module)
[9/3/2016, 4:16:49 PM] [netatmo platform] Initializing platform accessory 'Armstrong Atmo Station'...
[9/3/2016, 4:16:49 PM] [netatmo platform] Initializing platform accessory 'Armstrong Atmo Module'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘

**Comment by Alexis1537** [comment]
I think it's loading the platform fine but not loading home bridge properly. I suspect the "bridge code is in the wrong place. here's my code:


{"bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
"platforms": [{
        "platform": "netatmo",
        "name": "netatmo platform",
        "ttl": 5,
        "deviceTypes": [
                "weatherstation",
                "thermostat",
                "welcome"
        ],
        "auth": {
                "client_id": "xxxxxxxx",
                "client_secret": "xxxxxxxx",
                "username": "alexisxxxxxx",
                "password": "xxxxxxxx"
        }
}]
}

**Comment by planetk** [comment]
I gieß your config is fine now. Thinges like that Happen sometimes, when config changes.

You could try to reset the HomeKit settings ob the phone, stop the Server. Delete the persist and accessories directories in your homebridge Directory. Than Start the Server and connect your phone again

**Comment by Alexis1537** [comment]
Stefan, you are remarkable! Thank you do much. It works perfectly! Now I just have to work out to make use of it with Siri! Your patience and help are truly highly appreciated! Alex
